#!/bin/bash

branch=$1
branch=${branch##*/}

echo $branch


dir="hello-jenkins"
if [ -n $branch ] && [ "$branch" != "master" ]; then
	dir=${branch##*/}
fi
 
ssh xxx@172.18.37.198 <<EOF
  cd ~/${dir}
  git pull
  npm install --production
  forever restartall
  exit
EOF
